# Generated by Django 4.2.5 on 2023-09-09 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0008_facultycoursemapping_component_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facultycoursemapping',
            name='type',
            field=models.BooleanField(verbose_name='Faculty Type'),
        ),
    ]
